name: Package for all platforms

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Extract Maven project version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: project

    - name: Show extracted Maven project version
        run: echo ${{ steps.project.outputs.version }}
      
    - run: mkdir staging && cp target/lmark.jar staging
    
    # JPACKAGE build and compile
    - run: mkdir jpackage-temp && cp target/lmark.jar jpackage-temp
    
    - name: jpackage
      run : jpackage --type msi --name lmark --input jpackage-temp/ --main-jar lmark.jar --main-class com.lukeonuke.lmark.LMark --verbose --dest staging/app --description "lmark, the opensource markdown editor" --copyright "lukeonuke MIT 2021" --icon src/main/resources/icon.ico --vendor "LukeOnuke and contributors" --win-shortcut --win-menu --file-associations jpackage-configuration/FAmarkdown.properties --version ${{ steps.project.outputs.version }}
    
    - uses: actions/upload-artifact@v1
      with:
        name: WindowsPackage
        path: staging
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - run: mkdir staging && cp target/lmark*.jar staging
    
    # JPACKAGE build and compile
    - run: mkdir jpackage-temp && cp target/lmark.jar jpackage-temp
    
    - name: jpackage
      run : jpackage --name lmark --input jpackage-temp --main-jar lmark.jar --main-class com.lukeonuke.lmark.LMark --verbose --dest staging/app --description "lmark, the opensource markdown editor" --copyright "lukeonuke MIT 2021" --icon src/main/resources/icon.ico --linux-shortcut --vendor "LukeOnuke and contributors" --file-associations jpackage-configuration/FAmarkdown.properties
    
    - uses: actions/upload-artifact@v1
      with:
        name: LinuxPackage
        path: staging
  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - run: mkdir staging && cp target/lmark*.jar staging
    
    # JPACKAGE build and compile
    - run: mkdir jpackage-temp && cp target/lmark.jar jpackage-temp
    
    - name: jpackage
      run : jpackage --name lmark --input jpackage-temp --main-jar lmark.jar --main-class com.lukeonuke.lmark.LMark --verbose --dest staging/app --description "lmark, the opensource markdown editor" --copyright "lukeonuke MIT 2021" --icon src/main/resources/icon.ico --vendor "LukeOnuke and contributors" --file-associations jpackage-configuration/FAmarkdown.properties
    
    - uses: actions/upload-artifact@v1
      with:
        name: MacosPackage
        path: staging
